---
title: "Parrot_W_Synteny_Plot"
author: "Julia Levinstein"
date: "2026-10-09"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float: true
    highlight: tango
---

## 1. Configuration
```{r setup}
knitr::opts_knit$set(root.dir = "C:/Users/Julia/Desktop/IRT3")

library(ggplot2)
library(gggenomes)
library(tidyverse)

```

## 2. Load data
```{r}
#neo 
s <- read_csv("W_seq.csv")
f_neo <- read_csv("W_genes.csv")
l_neo <- read_csv("W_links.csv")


#ancestral

f_anc <- read_csv("ancestral_W_genes.csv")
l_anc <- read_csv("ancestral_W_links.csv")


#combine them

f_combined <- bind_rows(f_anc, f_neo)
l_combined <- bind_rows(l_anc, l_neo)


#add collumn to specify if it is neo or ancestral

f_neo <- read_csv("W_genes.csv") %>% mutate(source = "Neo")
f_anc <- read_csv("ancestral_W_genes.csv") %>% mutate(source = "Anc")

l_neo <- read_csv("W_links.csv") %>% mutate(source = "Neo")
l_anc <- read_csv("ancestral_W_links.csv") %>% mutate(source = "Anc")




```


## 3. Setting the species order
```{r}

#neo
species_levels <- readLines("species_order_W.txt")


s$bin_id <- factor(s$bin_id, levels = species_levels)


f_neo$bin_id <- factor(f_neo$bin_id, levels = species_levels)

l_neo$bin_id <- factor(l_neo$bin_id, levels = species_levels)
l_neo$bin_id2 <- factor(l_neo$bin_id2, levels = species_levels)

s <- s[order(match(s$bin_id, species_levels)), ]




#combined
species_levels <- readLines("species_order_W.txt")


f_combined$bin_id <- factor(f_combined$bin_id, levels = species_levels)
l_combined$bin_id <- factor(l_combined$bin_id, levels = species_levels)
l_combined$bin_id2 <- factor(l_combined$bin_id2, levels = species_levels)


s <- s[order(match(s$bin_id, species_levels)), ]

```

## 4. Flip sequences
```{r}
to_flip <- c("CM121528.1", "CM077908.1", "CM098573.1", "CM029940.1")

```

## 5. Plot only the neo genes
```{r}
p <- gggenomes(seqs = s, feats = f_neo, links = l_neo) %>%
  flip_seqs(all_of(to_flip)) + 
  geom_seq(linewidth = 0.5) +
  geom_bin_label() +
  geom_link(aes(fill = gene_id, colour = gene_id), alpha = 0.1, show.legend = FALSE) + 
  geom_gene(aes(fill = gene_id), size = 2, show.legend = FALSE) 

print(p)

```

## 6.Save plot
```{r}
ggsave("parrot_neoW_synteny.pdf", p, width = 18, height = 10)
```


# 7. ancestral W genes
```{r}

# Create the lists of IDs to highlight
anc_gene_ids <- unique(f_anc$gene_id)

```

## 8. plot
```{r}
p <- gggenomes(seqs = s, feats = f_combined, links = l_combined) %>%
  flip_seqs(all_of(to_flip)) + 
  geom_seq(linewidth = 0.3, color = "black") +
  geom_bin_label(size = 3.5) +
  
  geom_link(fill = "grey90", alpha = 0.2, show.legend = FALSE) + 
  geom_gene(fill = "#E66101", color= "#E66101", size = 3) + 
  
  geom_gene(data = genes(gene_id %in% anc_gene_ids), 
            fill = "#e6cc00", color = "#e6cc00", size = 3) +
  theme(legend.position = "none")

print(p)
```


## 9.Save plot
```{r}
ggsave("parrot_W_ancestral_synteny.pdf", p, width = 18, height = 10)

```

